### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by Souvikns** [Souvikns/JContainer#3]
We are using material-UI for theming, check **[this](https://material-ui.com/components/app-bar/)** for help.

## TODO
- [ ] Create a component `Navbar`. in the `component` folder
- [ ] User material-ui
- [ ] The Navbar will have only one route, `/api` . As this application is built on nextjs for routing check **[this](https://nextjs.org/docs/routing/introduction)**

**Comment by CptOrange16** [comment]
Hello, can I take on this issue?

**Comment by JoelLau** [comment]
@Souvikns did you mean "navbar" instead of "navar"?

**Comment by Souvikns** [comment]
@CptOrange16 go ahead this issue is yours. If you are looking for hactoberfest contribution make or after 1/oct

> @JoelLau thnx for pointing it out.

**Comment by CptOrange16** [comment]
Hey thanks for letting me contribute. 
I made a little navbar here but I'm having trouble with getting the app to run.

I've deployed the app with vercel just to see how it works/how it looks and I can't get past the login screen.
It asks for a passcode, but when i give one and click, nothing happens.

This could be because I did not configure the environmental variables as you say in the readme.md.
How can i configure them? Is there a file that I'm missing?

**Comment by Souvikns** [comment]
Yeah @CptOrange16 you need to pass your env variables.

**Comment by CptOrange16** [comment]
@Souvikns I pulled a fresh repo and have set the environment variables for the db into vercel using their tutorial.
The app there does not go past the login screen. When i click the button there are some errors:
![imagem](https://user-images.githubusercontent.com/4366792/94970613-f3979780-04fc-11eb-8350-eaa8a18be92d.png)

**Comment by Souvikns** [comment]
I have a vercel instance running and it is working fine. After login API_KEY is generated and is showing in the application.
![Screenshot 2020-10-03 at 3 09 07 AM](https://user-images.githubusercontent.com/41781438/94972052-fe1a5700-0525-11eb-84af-7495cbd82000.png)

From you above screenshot I can see as there are 502 errors, so it is clearly an internal error for sure. 
could you recheck once the env code that you have used and also I would suggest you use the deploy button in the readme.
Also pls double check for the env variables:

> Add mongodb url that looks like this mongodb+srv://<username>:<password>@cluster0.wudu9.mongodb.net/<database name>?retryWrites=true&w=majority in MONGO_URI
Add database name in place of DB_NAME.

---
> If still the problem persists then pls let me know. 
---

**Comment by Souvikns** [comment]
I have already added the navbar, so I am closing this.
