### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by Souvikns** [Souvikns/JContainer#4]
---
> This Issue is an **epic**, this is where all the tasks will be mentioned. Do not comment on this issue, please create your own issue linking this issue. 
---

## About 
I would like to start by speaking about what the project is doing. This is a self deployable **REST API** for storing JSON data. For now, the application lets the user create a `container`, and store JSON data in it. The application used HTTP requests to fetch and deliver data. 

## Process 
For making the process of documenting as easy as possible we are using `raw-loader` to load `.md` files and rendering with `react-markdown`. So for creating documentation we only have to create `.md` files in the `/markdown` folder. 

## TODO
- [ ] **Main index page** of the documentation, This is where we will have set up details and brief context of the application. 
- [ ] **Container route**, this is where we need to write about details about `container`
- [ ] **Document route** this is where we need to write about the details about **crud** operations to manage data. 

## Not to do 
- Try not to embed any links for relative pages as the pages will be loaded using react 
- Currently, there is no image support, so try not to add images.
