### ISSUE TITLE
Create Component for code documentation page

### ISSUE THREAD

**Issue by Souvikns** [Souvikns/JContainer#5]
---
> This Issue is an **epic**, this is where all the tasks will be mentioned. Do not comment on this issue, please create your own issue linking this issue. 
---

## About 
We are rendering the documentation page using `raw-loader` and `react-markdown`. So that we can fetch data from `.md` files directly. With the help of **next.js** we will server-side render the component by fetching the using `getStaticProps`, see [here](https://nextjs.org/docs/basic-features/data-fetching) for more details. 

## Possible Fix 
For loading different documents onto the screen we can use the state to manage which document to load and create a sidebar so that the user can use navigate easily. 

## Rough design
![Web 1920 – 1](https://user-images.githubusercontent.com/41781438/94445311-ead55780-01c4-11eb-9216-4c3faf286085.png)

## TODO
- [ ] Create Component for rendering documents. 
- [ ] Create a suitable logic to load and pass the data from the `.md` file to the component as props, using `getStaticProps`
- [ ] Build Component logic to conditionally rendering different documents. 
- [ ] Create Suitable **UI** for sidebar.
